//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chon
    {
        public int id_l { get; set; }
        public string the_loai { get; set; }
        public string ten { get; set; }
        public string tien { get; set; }
        public string ghichu { get; set; }
    }
}
