//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csdl1Entities : DbContext
    {
        public csdl1Entities()
            : base("name=csdl1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chon> chons { get; set; }
        public virtual DbSet<danhmuc_sp> danhmuc_sp { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<tk> tks { get; set; }
    }
}
