//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_pizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonban
    {
        public string mahdb { get; set; }
        public string makh { get; set; }
        public string tinhtrang { get; set; }
        public string ghichu { get; set; }
        public string diachi { get; set; }
        public System.DateTime ngaydat { get; set; }
    }
}
