//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_pizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public string makh { get; set; }
        public string tk { get; set; }
        public string mk { get; set; }
        public string tenkh { get; set; }
        public string Gioitinh { get; set; }
        public System.DateTime namsinh { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string vaitro { get; set; }
    }
}
