//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_pizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public string masp { get; set; }
        public string tensp { get; set; }
        public string donvi { get; set; }
        public string mota { get; set; }
        public string hinhanh { get; set; }
        public string maloai { get; set; }
    }
}
